<a href="https://colab.research.google.com/github/minalbansal14/Pytorch/blob/main/pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
# construct model class single layer
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self,num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out= self.sigmoid(out)

    return out


In [13]:
features = torch.rand(10,5)
model= Model(features.shape[1])

model(features)

tensor([[0.4723],
        [0.5660],
        [0.5317],
        [0.4825],
        [0.5232],
        [0.5230],
        [0.5124],
        [0.4730],
        [0.4198],
        [0.5681]], grad_fn=<SigmoidBackward0>)

In [14]:
model.linear.weight

Parameter containing:
tensor([[-0.2197, -0.2204,  0.4285, -0.3320,  0.2059]], requires_grad=True)

In [15]:
model.linear.bias

Parameter containing:
tensor([0.2228], requires_grad=True)

In [16]:
!pip install torchinfo

In [17]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [18]:
# construct model class one hidden layer
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self,num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear1(features)
    out= self.relu(out)
    out = self.linear2(out)
    out= self.sigmoid(out)

    return out

In [19]:
features = torch.rand(10,5)
model= Model(features.shape[1])

model(features)

tensor([[0.3730],
        [0.3583],
        [0.3235],
        [0.3611],
        [0.3730],
        [0.3715],
        [0.3730],
        [0.3506],
        [0.3730],
        [0.3730]], grad_fn=<SigmoidBackward0>)

In [21]:
model.linear1.weight

Parameter containing:
tensor([[-0.0167,  0.3267, -0.2635, -0.0736, -0.3455],
        [ 0.1127,  0.2203, -0.2949,  0.0448, -0.2551],
        [-0.3490,  0.3336, -0.1652,  0.0893,  0.3338]], requires_grad=True)

In [22]:
model.linear2.weight

Parameter containing:
tensor([[-0.4639, -0.2167, -0.3845]], requires_grad=True)

In [23]:
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [24]:
# construct model class using Sequential
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self,num_features):

    super().__init__()
    self.network=nn.Sequential(
      nn.Linear(num_features, 3),
      nn.ReLU(),
      nn.Linear(3, 1),
      nn.Sigmoid()

    )
  def forward(self, features):

    out = self.network(features)

    return out

In [25]:
features = torch.rand(10,5)
model= Model(features.shape[1])

model(features)

tensor([[0.5690],
        [0.5437],
        [0.5417],
        [0.5518],
        [0.5465],
        [0.5473],
        [0.5398],
        [0.5523],
        [0.5398],
        [0.5472]], grad_fn=<SigmoidBackward0>)