In [10]:
import torch

# Check if MPS (Metal Performance Shaders) is available
device = torch.device("mps") if torch.backends.mps.is_available() else torch.device("cpu")
print(f"Using device: {device}")

Using device: mps


In [11]:
# 1. Creating Tensors
tensor_1 = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32).to(device)
tensor_2 = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32).to(device)

print("Tensor 1:\n", tensor_1.cpu().numpy())  # Moving to CPU for printing
print("Tensor 2:\n", tensor_2.cpu().numpy())

Tensor 1:
 [[1. 2.]
 [3. 4.]]
Tensor 2:
 [[5. 6.]
 [7. 8.]]


In [12]:
# 2. Basic Arithmetic Operations
sum_tensor = tensor_1 + tensor_2
diff_tensor = tensor_1 - tensor_2
prod_tensor = tensor_1 * tensor_2  # Element-wise multiplication
div_tensor = tensor_1 / tensor_2   # Element-wise division

print("Sum:\n", sum_tensor.cpu().numpy())
print("Difference:\n", diff_tensor.cpu().numpy())
print("Element-wise Product:\n", prod_tensor.cpu().numpy())
print("Element-wise Division:\n", div_tensor.cpu().numpy())

Sum:
 [[ 6.  8.]
 [10. 12.]]
Difference:
 [[-4. -4.]
 [-4. -4.]]
Element-wise Product:
 [[ 5. 12.]
 [21. 32.]]
Element-wise Division:
 [[0.2        0.33333334]
 [0.42857143 0.5       ]]


In [13]:
# 3. Matrix Multiplication
matmul_result = torch.matmul(tensor_1, tensor_2)
print("Matrix Multiplication:\n", matmul_result.cpu().numpy())

Matrix Multiplication:
 [[19. 22.]
 [43. 50.]]


In [14]:
# 4. Reshaping Tensors
reshaped_tensor = tensor_1.view(4, 1)
print("Reshaped Tensor:\n", reshaped_tensor.cpu().numpy())

Reshaped Tensor:
 [[1.]
 [2.]
 [3.]
 [4.]]


In [15]:
# 5. Stacking Tensors
stacked_tensor = torch.stack((tensor_1, tensor_2), dim=0)
print("Stacked Tensor:\n", stacked_tensor.cpu().numpy())

Stacked Tensor:
 [[[1. 2.]
  [3. 4.]]

 [[5. 6.]
  [7. 8.]]]


In [16]:
# 6. Slicing & Indexing
indexed_tensor = tensor_1[:, 1]
print("Indexed Tensor (Second Column):\n", indexed_tensor.cpu().numpy())

Indexed Tensor (Second Column):
 [2. 4.]


In [17]:
# 7. AutoGrad & Backpropagation (ensure it's done on CPU since MPS may have limitations)
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2 + 2 * x + 1  # Function: f(x) = x^2 + 2x + 1
y.backward()  # Computes dy/dx
print("Gradient of y with respect to x:", x.grad)

Gradient of y with respect to x: tensor(8.)


In [18]:
# 8. Random Tensors
rand_tensor = torch.rand((3, 3), device=device)
print("Random Tensor:\n", rand_tensor.cpu().numpy())

Random Tensor:
 [[0.93593764 0.6900867  0.984221  ]
 [0.49475253 0.9059149  0.01065338]
 [0.9662694  0.12467003 0.01248527]]


In [19]:
# 9. Saving and Loading Tensors
torch.save(tensor_1.cpu(), "tensor.pth")  # Save on CPU to avoid compatibility issues
loaded_tensor = torch.load("tensor.pth").to(device)
print("Loaded Tensor:\n", loaded_tensor.cpu().numpy())

Loaded Tensor:
 [[1. 2.]
 [3. 4.]]


/var/folders/85/k6n4vd4179v0s7gvq1lm7jgw0000gn/T/ipykernel_2775/1491058499.py:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  loaded_tensor = torch.load("tensor.pth").to(de