## $\color{orangered}{\textbf{Tesnor Operations - PyTorch(1)}}$

In [1]:
import torch

In [2]:
tensor0d = torch.tensor(1)     #Creates a zero-dimensional tensor (scalar) from a Python integer
 
tensor1d = torch.tensor([1, 2, 3])    #Creates a one-dimensional tensor (vector) from a Python list

tensor2d = torch.tensor([[1, 2], 
                         [3, 4]])     #Creates a two-dimensional tensor from a nested Python list

tensor3d = torch.tensor([[[1, 2], [3, 4]], 
                         [[5, 6], [7, 8]]])    #Creates a three-dimensional tensor from a nested Python list

In [10]:
tensor0d

tensor(1)

In [11]:
tensor1d

tensor([1, 2, 3])

In [12]:
tensor2d


tensor([[1, 2],
        [3, 4]])

In [13]:
tensor3d

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [15]:
tensor0d * tensor1d

tensor([1, 2, 3])

In [16]:
tensor1d*tensor2d

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [18]:
tensor2d*tensor3d

tensor([[[ 1,  4],
         [ 9, 16]],

        [[ 5, 12],
         [21, 32]]])

### $\color{orangered}{\textbf{Tensor Transpose operation: .T}}$

In [19]:
tensor2d.T

tensor([[1, 3],
        [2, 4]])

In [20]:
tensor3d.T

/var/folders/85/k6n4vd4179v0s7gvq1lm7jgw0000gn/T/ipykernel_46828/4138490363.py:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/TensorShape.cpp:3687.)
  tensor3d.T


tensor([[[1, 5],
         [3, 7]],

        [[2, 6],
         [4, 8]]])

### $\color{orangered}{\textbf{Changing Tensor elements: ".reshape" and ".view"}}$

The subtle difference between .view() and .reshape() in PyTorch lies in their handling of memory layout: .view() requires the original data to be contiguous and will fail if it isn’t, whereas .reshape() will work regardless, copying the data if necessary to ensure the desired shape.

In [26]:
tensor2d = torch.tensor([[1, 2, 3], 
                         [4, 5, 6]])
tensor2d

tensor([[1, 2, 3],
        [4, 5, 6]])

In [27]:
tensor2d.shape #shape attribute allows us to access the shape of a tensor means 2nd tesnor has 2 rows and 2 coloumns 

torch.Size([2, 3])

As you can see, **.shape** returns [2, 3], meaning the tensor has two rows and three columns. To **reshape** the tensor into a 3 × 2 tensor, we can use the .reshape method:



In [28]:
tensor2d.reshape(3, 2) 

tensor([[1, 2],
        [3, 4],
        [5, 6]])